# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT BOOT_FLASH CACHE STRING "Type of multi-context")
#-----------------------Build FSBL Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*FSBL.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " FSBL)
    ExternalProject_Add(nucleo-n657x0-q_FSBL
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/FSBL/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/FSBL
        PREFIX                      FSBL
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/FSBL/build")
	set(ST_BOOT_FLASH_FSBL_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/FSBL/build/nucleo-n657x0-q_FSBL${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to fsbl project target")
endif()

